#pragma once
#include <string>

// ═══════════════════════════════════════════════════════════════════════
//  ALERT.H
//  Represents a single system notification for the student.
//  Alerts are generated by DegreeAudit — never by the student directly.
//  Once created they are read-only except for deactivation.
//
//  toJson() now emits "title" and "action" fields in addition to the
//  original "type", "message", "courseCode", and "active" fields.
//  These extra fields are what alerts.html needs to render full cards.
// ═══════════════════════════════════════════════════════════════════════

enum class AlertType {
	// Student's GPA has dropped below the 2.0 minimum threshold.
	GPA_WARNING,

	// Student has not completed the prerequisite for a course
	// they are attempting or are next in line to take.
	PREREQ_NOT_MET,

	// Student is missing a course that is specifically required
	// by their degree plan with no substitution allowed.
	MANDATORY_NOT_MET,

	// Student has not accumulated enough credit hours
	// in a required category (Math, Science, etc.).
	HOURS_NOT_MET,

	// Student is now eligible to take this course —
	// all prerequisites have been satisfied.
	ELIGIBLE_COURSE,

	// Student attempted to assign the same course
	// to satisfy two different degree requirements.
	COURSE_REUSED
};

class Alert {
private:
	AlertType   type;
	std::string message;
	std::string courseCode;
	bool        active;

	// Converts the enum to its raw string name ("GPA_WARNING" etc.).
	std::string alertTypeToString() const;

	// Returns a short card heading for this alert type.
	// Example: PREREQ_NOT_MET → "Prerequisite Not Met"
	std::string titleForType() const;

	// Returns a suggested action button label for this alert type.
	// Example: ELIGIBLE_COURSE → "Register Now"
	std::string actionForType() const;

public:
	// ───────────────────────────────────────────────────────────────────
	//  CONSTRUCTORS
	// ───────────────────────────────────────────────────────────────────

	Alert();

	// courseCode defaults to empty for alerts not tied to a specific course.
	Alert(AlertType type, const std::string& message,
		const std::string& courseCode = "");

	// ───────────────────────────────────────────────────────────────────
	//  GETTERS
	// ───────────────────────────────────────────────────────────────────

	AlertType   getType()       const;
	std::string getMessage()    const;
	std::string getCourseCode() const;
	bool        isActive()      const;

	// ───────────────────────────────────────────────────────────────────
	//  ACTIONS
	// ───────────────────────────────────────────────────────────────────

	// Marks this alert as inactive.
	void deactivate();

	// ───────────────────────────────────────────────────────────────────
	//  SERIALIZATION
	// ───────────────────────────────────────────────────────────────────

	// Converts this alert to a JSON string.
	// Emits: type, title, message, courseCode, action, active.
	// Example:
	// {
	//   "type":       "PREREQ_NOT_MET",
	//   "title":      "Prerequisite Not Met",
	//   "message":    "Prerequisite not met for CMPS3013...",
	//   "courseCode": "CMPS3013",
	//   "action":     "View Schedule",
	//   "active":     true
	// }
	std::string toJson() const;
};
