#include "Alert.h"

// ═══════════════════════════════════════════════════════════════════════
//  ALERT.CPP
//  Implements the Alert class — a single system notification for the
//  student. Alerts are generated by DegreeAudit — never by the student
//  directly. Once created they are read-only except for deactivation.
//
//  toJson() now emits two extra fields the alerts.html page needs:
//    "title"  — a short human-readable label derived from the type
//    "action" — a suggested next-step button label
//  The "date" field from the previous gap analysis has been intentionally
//  omitted per project requirements.
// ═══════════════════════════════════════════════════════════════════════

// ───────────────────────────────────────────────────────────────────────
//  CONSTRUCTORS
// ───────────────────────────────────────────────────────────────────────

Alert::Alert()
	: type(AlertType::GPA_WARNING), message(""), courseCode(""), active(true) {
}

Alert::Alert(AlertType type, const std::string& message, const std::string& courseCode)
	: type(type), message(message), courseCode(courseCode), active(true) {
}

// ───────────────────────────────────────────────────────────────────────
//  GETTERS
// ───────────────────────────────────────────────────────────────────────

AlertType   Alert::getType()       const { return type; }
std::string Alert::getMessage()    const { return message; }
std::string Alert::getCourseCode() const { return courseCode; }
bool        Alert::isActive()      const { return active; }

// ───────────────────────────────────────────────────────────────────────
//  ACTIONS
// ───────────────────────────────────────────────────────────────────────

void Alert::deactivate() {
	active = false;
}

// ───────────────────────────────────────────────────────────────────────
//  PRIVATE HELPERS
// ───────────────────────────────────────────────────────────────────────

// Converts the AlertType enum to the raw type string sent in JSON.
// JavaScript receives "GPA_WARNING" not the integer 0.
std::string Alert::alertTypeToString() const {
	if (type == AlertType::GPA_WARNING)       return "GPA_WARNING";
	if (type == AlertType::PREREQ_NOT_MET)    return "PREREQ_NOT_MET";
	if (type == AlertType::MANDATORY_NOT_MET) return "MANDATORY_NOT_MET";
	if (type == AlertType::HOURS_NOT_MET)     return "HOURS_NOT_MET";
	if (type == AlertType::ELIGIBLE_COURSE)   return "ELIGIBLE_COURSE";
	if (type == AlertType::COURSE_REUSED)     return "COURSE_REUSED";
	return "UNKNOWN";
}

// Returns a short human-readable title for the alert card heading.
// alerts.html reads alert.title directly — if it is missing the card
// falls back to alert.message which is longer and less suitable as a heading.
std::string Alert::titleForType() const {
	if (type == AlertType::GPA_WARNING)       return "GPA Below Minimum";
	if (type == AlertType::PREREQ_NOT_MET)    return "Prerequisite Not Met";
	if (type == AlertType::MANDATORY_NOT_MET) return "Required Course Missing";
	if (type == AlertType::HOURS_NOT_MET)     return "Credit Hours Not Met";
	if (type == AlertType::ELIGIBLE_COURSE)   return "Course Now Available";
	if (type == AlertType::COURSE_REUSED)     return "Course Already Used";
	return "System Alert";
}

// Returns a short suggested action label for the alert card button.
// alerts.html renders this as the primary action button if non-empty.
// Gives the student a clear next step without reading the full message.
std::string Alert::actionForType() const {
	if (type == AlertType::GPA_WARNING)       return "View Degree Audit";
	if (type == AlertType::PREREQ_NOT_MET)    return "View Schedule";
	if (type == AlertType::MANDATORY_NOT_MET) return "View Degree Audit";
	if (type == AlertType::HOURS_NOT_MET)     return "View Degree Audit";
	if (type == AlertType::ELIGIBLE_COURSE)   return "Register Now";
	if (type == AlertType::COURSE_REUSED)     return "View Degree Audit";
	return "";
}

// ───────────────────────────────────────────────────────────────────────
//  SERIALIZATION
// ───────────────────────────────────────────────────────────────────────

// Converts this alert to a JSON string for the frontend.
// Fields:
//   type        — raw enum string e.g. "GPA_WARNING"
//   title       — short heading e.g. "GPA Below Minimum"
//   message     — full description (used as "description" by the card)
//   courseCode  — course that triggered the alert, or "" if not applicable
//   action      — suggested button label e.g. "View Degree Audit"
//   active      — boolean, always true when first created
//
// Example output:
// {
//   "type":       "PREREQ_NOT_MET",
//   "title":      "Prerequisite Not Met",
//   "message":    "Prerequisite not met for CMPS3013...",
//   "courseCode": "CMPS3013",
//   "action":     "View Schedule",
//   "active":     true
// }
std::string Alert::toJson() const {
	std::string json = "{";

	json += "\"type\":\""       + alertTypeToString() + "\",";
	json += "\"title\":\""      + titleForType()      + "\",";
	json += "\"message\":\""    + message             + "\",";
	json += "\"courseCode\":\"" + courseCode          + "\",";
	json += "\"action\":\""     + actionForType()     + "\",";
	json += "\"active\":"       + std::string(active ? "true" : "false");

	json += "}";
	return json;
}
