#include "Alert.h"

// ═══════════════════════════════════════════════════════════════════════
//  ALERT.CPP
//  Implements the Alert class — a single system notification for the
//  student. Each alert has a type, message, and optional course code.
//  Alerts are generated by DegreeAudit and the GPA checker — never
//  by the student directly. Once created they are read-only except for
//  deactivation. Active alerts are displayed on the frontend dashboard
//  until cleared or deactivated.
// ═══════════════════════════════════════════════════════════════════════

// ───────────────────────────────────────────────────────────────────────
//  CONSTRUCTORS
// ───────────────────────────────────────────────────────────────────────

// Default constructor.
// Defaults to GPA_WARNING type as a safe placeholder.
// Active starts as true — every alert is active when first created.
Alert::Alert()
	: type(AlertType::GPA_WARNING), message(""), courseCode(""), active(true) {
}

// Parameterized constructor.
// courseCode is optional — GPA alerts pass empty string by default.
// Active always starts true — alerts are live the moment they are created.
Alert::Alert(AlertType type, const std::string& message, const std::string& courseCode)
	: type(type), message(message), courseCode(courseCode), active(true) {
}

// ───────────────────────────────────────────────────────────────────────
//  GETTERS
// ───────────────────────────────────────────────────────────────────────

// Returns the enum type of this alert.
// Used internally to compare and categorize alerts.
AlertType Alert::getType() const {
	return type;
}

// Returns the human readable message shown to the student.
std::string Alert::getMessage() const {
	return message;
}

// Returns the course code that triggered this alert.
// Returns empty string if this alert is not course-specific (e.g. GPA_WARNING).
std::string Alert::getCourseCode() const {
	return courseCode;
}

// Returns true if this alert is currently active and should be displayed.
bool Alert::isActive() const {
	return active;
}

// ───────────────────────────────────────────────────────────────────────
//  ACTIONS
// ───────────────────────────────────────────────────────────────────────

// Marks this alert as inactive.
// Called when the condition that triggered it has been resolved.
// Example: student's GPA rises above 2.0 → deactivate GPA_WARNING.
// Inactive alerts are hidden on the frontend but kept in history.
void Alert::deactivate() {
	active = false;
}

// ───────────────────────────────────────────────────────────────────────
//  PRIVATE HELPERS
// ───────────────────────────────────────────────────────────────────────

// Converts the AlertType enum to a human readable string.
// Called by toJson() so JavaScript receives "GPA_WARNING" not "0".
// Without this the frontend gets meaningless integers and cannot
// determine how to style or respond to each alert type.
std::string Alert::alertTypeToString() const {
	if (type == AlertType::GPA_WARNING)       return "GPA_WARNING";
	if (type == AlertType::PREREQ_NOT_MET)    return "PREREQ_NOT_MET";
	if (type == AlertType::MANDATORY_NOT_MET) return "MANDATORY_NOT_MET";
	if (type == AlertType::HOURS_NOT_MET)     return "HOURS_NOT_MET";
	if (type == AlertType::ELIGIBLE_COURSE)   return "ELIGIBLE_COURSE";
	if (type == AlertType::COURSE_REUSED)     return "COURSE_REUSED";

	// Fallback for any future alert types not yet handled.
	return "UNKNOWN";
}

// ───────────────────────────────────────────────────────────────────────
//  SERIALIZATION
// ───────────────────────────────────────────────────────────────────────

// Converts this alert into a JSON string for the frontend.
// Called by Student::toJson() when building the alerts array.
// Type is sent as a readable string via alertTypeToString() so
// JavaScript can use it directly in if checks without a lookup table.
//
// Example output:
// {
//   "type":       "PREREQ_NOT_MET",
//   "message":    "Prerequisite not met for CMPS3013",
//   "courseCode": "CMPS3013",
//   "active":     true
// }
std::string Alert::toJson() const {
	std::string json = "{";

	// Convert enum to readable string — JavaScript needs "GPA_WARNING" not "0".
	json += "\"type\":\"" + alertTypeToString() + "\",";
	json += "\"message\":\"" + message + "\",";
	json += "\"courseCode\":\"" + courseCode + "\",";

	// Boolean — JSON requires lowercase true/false not quoted strings.
	json += "\"active\":" + std::string(active ? "true" : "false");

	json += "}";
	return json;
}