#pragma once
#include <string>

// ═══════════════════════════════════════════════════════════════════════
//  ALERT.H
//  Represents a single system notification for the student.
//  Alerts are generated by DegreeAudit and the GPA checker —
//  never by the student directly. Once created they are read-only
//  except for deactivation. Active alerts are displayed on the
//  frontend dashboard until cleared or deactivated.
// ═══════════════════════════════════════════════════════════════════════

// Defines every possible alert category the system can generate.
// Using enum class instead of strings prevents typos from causing
// silent bugs — the compiler rejects any invalid alert type.
enum class AlertType {
	// Student's GPA has dropped below the 2.0 minimum threshold.
	GPA_WARNING,

	// Student has not completed the prerequisite for a course
	// they are attempting or are next in line to take.
	PREREQ_NOT_MET,

	// Student is missing a course that is specifically required
	// by their degree plan with no substitution allowed.
	MANDATORY_NOT_MET,

	// Student has not accumulated enough credit hours
	// in a required category (Math, Science, etc.).
	HOURS_NOT_MET,

	// Student is now eligible to take this course —
	// all prerequisites have been satisfied.
	ELIGIBLE_COURSE,

	// Student attempted to assign the same course
	// to satisfy two different degree requirements.
	COURSE_REUSED
};

class Alert {
private:
	// The category of this alert — drives frontend styling and
	// determines how the message is interpreted.
	AlertType type;

	// Human readable description shown to the student.
	// Example: "Your GPA has fallen below 2.0"
	std::string message;

	// The course code that triggered this alert, if applicable.
	// GPA_WARNING leaves this empty — all others reference a course.
	// Example: "CMPS3013" for a PREREQ_NOT_MET alert.
	std::string courseCode;

	// Whether this alert is currently active.
	// Inactive alerts are kept in history but hidden on the frontend.
	bool active;

	//
	std::string alertTypeToString() const;

public:
	// ───────────────────────────────────────────────────────────────────
	//  CONSTRUCTORS
	// ───────────────────────────────────────────────────────────────────

	// Default constructor.
	// Creates an inactive alert with no message or course code.
	Alert();

	// Parameterized constructor.
	// courseCode defaults to empty string for alerts like GPA_WARNING
	// that are not tied to a specific course.
	Alert(AlertType type, const std::string& message,
		const std::string& courseCode = "");

	// ───────────────────────────────────────────────────────────────────
	//  GETTERS
	// ───────────────────────────────────────────────────────────────────

	// Returns the type of this alert.
	// Used by the frontend to determine styling and icon.
	AlertType getType() const;

	// Returns the human readable alert message.
	std::string getMessage() const;

	// Returns the course code that triggered this alert.
	// Returns empty string if alert is not course-specific.
	std::string getCourseCode() const;

	// Returns true if this alert is currently active.
	bool isActive() const;

	// ───────────────────────────────────────────────────────────────────
	//  ACTIONS
	// ───────────────────────────────────────────────────────────────────

	// Marks this alert as inactive.
	// Called when the condition that triggered it has been resolved.
	// Example: GPA rises above 2.0 → deactivate GPA_WARNING alert.
	void deactivate();

	// ───────────────────────────────────────────────────────────────────
	//  SERIALIZATION
	// ───────────────────────────────────────────────────────────────────

	// Converts this alert to a JSON string for the frontend.
	// Called by Student::toJson() when building the alerts array.
	// Example output:
	// {
	//   "type":       "PREREQ_NOT_MET",
	//   "message":    "Prerequisite not met for CMPS3013",
	//   "courseCode": "CMPS3013",
	//   "active":     true
	// }
	std::string toJson() const;
};