#include "Student.h"

// ═══════════════════════════════════════════════════════════════════════
//  STUDENT.CPP
//  Implements the Student class the core entity of the advising system.
//  A Student owns their academic records, tracks their GPA and credit
//  hours, and holds any active alerts generated by the system.
// ═══════════════════════════════════════════════════════════════════════

// ───────────────────────────────────────────────────────────────────────
//  CONSTRUCTORS
// ───────────────────────────────────────────────────────────────────────

// Default Constructor
// Used when the program launches and no student data exists yet.
// Sets safe starting values so nothing is left uninitialized.
// The frontend will prompt the user to fill in their info via setters.
Student::Student()
	: name(" "), major("undecided"), gpa(0.0), totalCreditHours(0) {
}

// Parameterized Constructor
// Used when a first-time user submits their name and major through
// the frontend form. GPA and credit hours always start at zero —
// they are computed from academic records, never entered manually.
Student::Student(const std::string& name, const std::string& major)
	: name(name), major(major), gpa(0.0), totalCreditHours(0) {
}

// ───────────────────────────────────────────────────────────────────────
//  GETTERS
//  All getters are marked const — they promise not to modify the object.
//  The vector getters come in two versions:
//    const ref  → for reading only (e.g. passing to DegreeAudit)
//    normal ref → for modifying (e.g. adding/removing records)
// ───────────────────────────────────────────────────────────────────────

// Returns the student's full name.
std::string Student::getName() const { return name; }

// Returns the student's declared major.
std::string Student::getMajor() const { return major; }

// Returns the student's current GPA.
// NOTE: This value is always up to date — calculateGPA() is called
// automatically any time a record is added, removed, or updated.
double Student::getGpa() const { return gpa; }

// Returns total credit hours accumulated across all academic records.
// Used by DegreeAudit to measure progress toward degree completion.
int Student::getTotalCreditHours() const { return totalCreditHours; }

// Read-only access to academic records.
// Used when we need to inspect records without risking modification
// (e.g. when DegreeAudit scans completed courses).
const std::vector<AcademicRecord>& Student::getRecords() const { return records; }

// Mutable access to academic records.
// Used internally when records need to be modified directly.
std::vector<AcademicRecord>& Student::getRecords() { return records; }

// Read-only access to the student's active alerts.
// Used by the frontend to display warnings without modifying them.
const std::vector<Alert>& Student::getAlerts() const { return alerts; }

// Mutable access to alerts.
// Used when the alert system needs to add or clear alerts.
std::vector<Alert>& Student::getAlerts() { return alerts; }

// ───────────────────────────────────────────────────────────────────────
//  SETTERS
//  Allow the student to update their profile information.
//  this-> is required here because the parameter names match the
//  private member names — without it, C++ can't tell them apart.
// ───────────────────────────────────────────────────────────────────────

// Updates the student's name (e.g. if entered incorrectly at first launch).
void Student::setName(const std::string& name) { this->name = name; }

// Updates the student's major (e.g. if they change degree plans).
void Student::setMajor(const std::string& major) { this->major = major; }

// ───────────────────────────────────────────────────────────────────────
//  ACADEMIC RECORD MANAGEMENT
//  These three methods form the CRUD core for a student's course history.
//  Every method that changes records calls calculateGPA() immediately
//  after so the student's GPA and credit hours are never stale.
// ───────────────────────────────────────────────────────────────────────

// Adds a new course record to the student's history.
// Called when a student logs a course they have completed.
// Automatically recalculates GPA after insertion.
void Student::addRecord(const AcademicRecord& record) {
	records.push_back(record);  // append to end of the records vector
	calculateGPA();             // keep GPA current immediately
}

// Removes a course record by course code.
// Called when a student deletes a course entry entirely.
// Uses an iterator because vector::erase() requires one — you cannot
// erase by index directly in a range-based for loop.
void Student::removeRecord(const std::string& courseCode) {
	for (auto it = records.begin(); it != records.end(); ++it) {
		if (it->getCourseCode() == courseCode) {
			records.erase(it);  // remove this element, iterator now invalid
			calculateGPA();     // recalculate since credit hours changed
			return;             // exit immediately — iterator is now invalid
		}
	}
	// If courseCode wasn't found, nothing happens (silent no-op).
	// Future improvement: return a bool or throw to signal "not found".
}

// Updates the grade for an existing course record.
// Called when a student re-enters a course with a better or corrected grade.
// Uses a range-based for loop with a reference (auto&) so changes
// apply to the actual record, not a copy of it.
void Student::updateRecord(const std::string& courseCode, const std::string& newGrade) {
	for (auto& record : records) {                      // auto& = reference, not copy
		if (record.getCourseCode() == courseCode) {
			record.setGrade(newGrade);                  // update grade on the real object
			calculateGPA();                             // new grade changes GPA
			return;                                     // stop after first match
		}
	}
	// If courseCode wasn't found, nothing happens (silent no-op).
}

// ───────────────────────────────────────────────────────────────────────
//  GPA CALCULATION
//  Computes a credit-weighted GPA from all academic records.
//
//  Formula:
//    GPA = sum(gradePoints × creditHours) / sum(creditHours)
//
//  Example:
//    CS301  3 credits  A  (4.0) → 12.0 quality points
//    ENG101 3 credits  B+ (3.3) →  9.9 quality points
//    PE101  1 credit   A  (4.0) →  4.0 quality points
//    ─────────────────────────────────────────────────
//    Total  7 credits           → 25.9 quality points
//    GPA = 25.9 / 7 = 3.7
//
//  This method is private in effect — only called internally after
//  any record change. Never called directly by the frontend.
// ───────────────────────────────────────────────────────────────────────
void Student::calculateGPA() {
	// Edge case: no records means no GPA and no credit hours.
	if (records.empty()) {
		gpa = 0.0;
		totalCreditHours = 0;
		return;
	}

	double totalPoints = 0.0;  // sum of (gradePoints × creditHours)
	int    totalCredits = 0;    // sum of all credit hours attempted

	for (const auto& record : records) {
		int    credits = record.getCreditHours();   // e.g. 3
		double points = record.getGradePoints();   // e.g. 3.3 for B+
		totalPoints += points * credits;           // weighted contribution
		totalCredits += credits;                    // running credit total
	}

	totalCreditHours = totalCredits;

	// Ternary guard: avoid dividing by zero if somehow credits are 0.
	gpa = (totalCredits > 0) ? (totalPoints / totalCredits) : 0.0;
}

// ───────────────────────────────────────────────────────────────────────
//  ALERT MANAGEMENT
//  Alerts are generated externally (by the Alert system) and pushed
//  into the student's alert list. The student doesn't create its own
//  alerts — it just stores and clears them.
// ───────────────────────────────────────────────────────────────────────

// Adds a new alert to the student's alert list.
// Called by the alert checking system after calculateGPA() runs
// and detects the GPA has dropped below 2.0.
void Student::addAlert(const Alert& alert) {
	alerts.push_back(alert);
}

// Clears all active alerts.
// Called before re evaluating alerts so we don't stack duplicates.
// Example flow: grade updated -> clearAlerts() -> checkAlerts() -> addAlert() if needed.
void Student::clearAlerts() {
	alerts.clear();
}

// ───────────────────────────────────────────────────────────────────────
//  SERIALIZATION
//  Converts the entire Student object into a JSON string so the
//  cpp-httplib server can send it to the JavaScript frontend.
//
//  The frontend receives this string, calls JSON.parse(), and can
//  immediately access student.name, student.gpa, student.records, etc.
//
//  Records and alerts are nested JSON arrays  each item calls its
//  own toJson() method, which is why every class in this project
//  implements toJson().
// ───────────────────────────────────────────────────────────────────────
std::string Student::toJson() const {
	std::string json = "{";

	// ── Scalar fields ──────────────────────────────────────────────────
	json += "\"name\":\"" + name + "\",";
	json += "\"major\":\"" + major + "\",";
	json += "\"gpa\":" + std::to_string(gpa) + ",";
	json += "\"totalCreditHours\":" + std::to_string(totalCreditHours) + ",";

	// ── Academic records array ─────────────────────────────────────────
	// Each AcademicRecord serializes itself via its own toJson().
	// Commas are added between items but NOT after the last one
	// trailing commas are invalid JSON and will break JSON.parse().
	json += "\"records\":[";
	for (size_t i = 0; i < records.size(); i++) {
		json += records[i].toJson();
		if (i < records.size() - 1) json += ",";  // comma between items only
	}
	json += "],";

	// ─---─ Alerts array ───────────────────────────────────────────────────
	// same pattern as records  each Alert serializes itself
	json += "\"alerts\":[";
	for (size_t i = 0; i < alerts.size(); i++) {
		json += alerts[i].toJson();

		// comma between items only slove traiing comma issue
		if (i < alerts.size() - 1) json += ",";
	}
	json += "]";  // no trailing comma this is the last field

	json += "}";
	return json;
}